// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'children': string;
  'formContainer': string;
  'step': string;
  'stepButtonContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
