// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caret': string;
  'clear-btn': string;
  'container': string;
  'divider': string;
  'highlight': string;
  'option': string;
  'options': string;
  'selected': string;
  'show': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
