// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'img1': string;
  'img2': string;
  'img3': string;
  'text1': string;
  'text2': string;
  'text3': string;
}
export const cssExports: CssExports;
export default cssExports;
